version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    depends_on:
      - clamav

  clamav:
    image: clamav/clamav:latest
    ports:
      - "3310:3310"

